var pattern=['오전1','오전2','오전3','오전4','오전5','휴','휴','심야1','심야2','심야3','심야4','심야5','휴','휴','오후1','오후2','오후3','오후4','오후5','휴'];
var PATTERN_LEN=pattern.length;
var BASE_DATE_2=new Date(2025,7,7);
var CREW_OFFSETS={'2':0,'1':5,'4':10,'3':15};
var HOL_EMBED={"2025": {"2025-01-01": "신정", "2025-01-28": "설날", "2025-01-29": "설날", "2025-01-30": "설 대체휴일", "2025-03-01": "삼일절", "2025-05-05": "어린이날", "2025-05-06": "어린이날 대체휴일", "2025-06-06": "현충일", "2025-08-15": "광복절", "2025-10-03": "개천절", "2025-10-06": "추석", "2025-10-07": "추석", "2025-10-08": "추석 대체휴일", "2025-10-09": "한글날", "2025-12-25": "성탄절"}, "2026": {"2026-01-01": "신정", "2026-02-16": "설날", "2026-02-17": "설날", "2026-02-18": "설 대체휴일", "2026-03-01": "삼일절", "2026-05-05": "어린이날", "2026-05-25": "석가탄신일", "2026-06-06": "현충일", "2026-08-15": "광복절", "2026-09-24": "추석", "2026-09-25": "추석", "2026-09-26": "추석 대체휴일", "2026-10-03": "개천절", "2026-10-09": "한글날", "2026-12-25": "성탄절"}};
function loadHolidays(year){return fetch('./holidays-crew.json?v=3',{cache:'no-store'}).then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(j){return j[String(year)]||(HOL_EMBED[String(year)]||{});}).catch(function(){return HOL_EMBED[String(year)]||{};});}
function ymd(d){var y=d.getFullYear(),m=('0'+(d.getMonth()+1)).slice(-2),da=('0'+d.getDate()).slice(-2);return y+'-'+m+'-'+da;}
function baseIndexOn(date){var a=new Date(date.getFullYear(),date.getMonth(),date.getDate());var diff=Math.floor((a-BASE_DATE_2)/(24*60*60*1000));return ((diff%PATTERN_LEN)+PATTERN_LEN)%PATTERN_LEN;}
function shiftOf(date,crew){var baseIdx=baseIndexOn(date);var offset=CREW_OFFSETS[String(crew)]||0;var idx=(baseIdx+offset)%PATTERN_LEN;return pattern[idx];}
function shiftClass(name){if(name.indexOf('오전')===0)return'morning';if(name.indexOf('오후')===0)return'evening';if(name.indexOf('심야')===0)return'night';return'off';}
var titleEl=document.getElementById('title'),daysEl=document.getElementById('days'),holistEl=document.getElementById('holist'),crewSel=document.getElementById('crew'),crewInfoEl=document.getElementById('crewInfo');
var view=new Date(),today=new Date();
function crewDesc(c){if(c==='1')return'오늘 기준: 심야1';if(c==='2')return'기준일 2025-08-07 = 오전1';if(c==='3')return'임시 오프셋(+15) · 필요 시 조정';if(c==='4')return'오늘 기준: 심야 후 첫 휴무1';return'';}
function render(){var y=view.getFullYear(),m0=view.getMonth(),m=m0+1;titleEl.textContent=y+'년 '+m+'월';crewInfoEl.textContent='선택 조: '+crewSel.value+'조 · '+crewDesc(crewSel.value);return loadHolidays(y).then(function(holidays){var first=new Date(y,m0,1);var lastDate=new Date(y,m,0).getDate();var blanks=(first.getDay()+7)%7;daysEl.innerHTML='';for(var i=0;i<blanks;i++){daysEl.appendChild(document.createElement('div'));}var monthH=[];for(var d=1;d<=lastDate;d++){var date=new Date(y,m0,d);var cell=document.createElement('div');cell.className='cell';var dateSpan=document.createElement('div');dateSpan.className='date';dateSpan.textContent=d;cell.appendChild(dateSpan);var shift=shiftOf(date,crewSel.value);var shiftEl=document.createElement('div');shiftEl.className='shift '+shiftClass(shift);shiftEl.textContent=(shift.indexOf('휴')===0)?'휴무':shift;cell.appendChild(shiftEl);var key=ymd(date);if(holidays[key]){var badge=document.createElement('div');badge.className='badge';badge.textContent=holidays[key];cell.appendChild(badge);monthH.push([key,holidays[key]]);}if(ymd(date)===ymd(today))cell.classList.add('today');var dow=date.getDay(),mondayOffset=(dow+6)%7,work=0;for(var k=0;k<=mondayOffset;k++){var chk=new Date(y,m0,d-mondayOffset+k);var s=shiftOf(chk,crewSel.value);if(s.indexOf('휴')!==0)work++;}if(work===6&&shift.indexOf('휴')!==0)cell.classList.add('sixth');daysEl.appendChild(cell);}if(monthH.length)holistEl.innerHTML='<b>이번 달 공휴일</b><ul>'+monthH.map(function(x){return'<li>'+x[0]+' — '+x[1]+'</li>';}).join('')+'</ul>';else holistEl.innerHTML='';});}
document.getElementById('prev').onclick=function(){view=new Date(view.getFullYear(),view.getMonth()-1,1);render();};
document.getElementById('next').onclick=function(){view=new Date(view.getFullYear(),view.getMonth()+1,1);render();};
document.getElementById('today').onclick=function(){view=new Date();render();};
document.getElementById('crew').onchange=function(){try{localStorage.setItem('crewSel',crewSel.value);}catch(e){}render();};
(function(){try{var saved=localStorage.getItem('crewSel');if(saved)crewSel.value=saved;}catch(e){}})();render();